#cloud-config
users:
  - name: ubuntu
    groups: sudo
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    shell: /bin/bash
    ssh_import_id: gh:tp4348

package_update: true
package_upgrade: true
packages:
  - sl
