name: 'Deploy IoC to Terraform Cloud'

on:
  push:
    branches:
    - master

env:
  TF_VAR_lxdremote_password: ${{ secrets.LXDREMOTE_PASSWORD }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    timeout-minutes: 10 # It's possible for LXD to hang
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform Format
      run: terraform fmt -check
    - name: Terraform Init
      run: terraform init
    - name: Terraform Validate
      run: terraform validate -no-color
    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
